server: 
  port: 9008
spring: 
  application:  
    name: 1024-user #指定服务名
  datasource:  
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.68.128:3306/tensquare_user?useUnicode=true&amp;characterEncoding=UTF8
    username: root
    password: admin123
  jpa: 
    database: MySQL
    show-sql: true
  rabbitmq:
    host: 192.168.68.128
  redis:
    host: 192.168.68.128